apiVersion: v1
kind: Service
metadata:
  name: adderservice
  labels:
    run: adderservice
spec:
  ports:
    - port: 8081
      name: main
      protocol: TCP
      targetPort: 8081
  selector:
    run: adderservice
  type: NodePort
