apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adderservice
spec:   
  replicas: 1
  template:
    metadata:
      labels:
        run: adderservice
    spec:
      containers:
      - name: adderservice
        image: madjava/adderservice
        ports:
        - containerPort: 8081